"""
Document generation and persistent document storage endpoints.

Generates a DOCX using the existing Documentation Agent, stores the
generated file in Supabase Storage, and streams the DOCX back to the
browser.
"""

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from google.genai import errors as genai_errors

from app.schemas.document import DocumentType
from app.services.document_service import generate_document_content, render_docx
from app.core.idea_repository import fetch_idea_with_student_context
from app.core.document_repository import save_document

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/documents", tags=["documents"])

DOCX_MEDIA_TYPE = (
    "application/vnd.openxmlformats-officedocument."
    "wordprocessingml.document"
)


@router.get("/{document_type}/{idea_id}")
def generate_document(document_type: DocumentType, idea_id: str):
    """
    Generate a fresh DOCX document from the latest project data.

    The document is:
    1. Generated by the Documentation Agent.
    2. Rendered as a real DOCX file.
    3. Saved permanently in Supabase Storage.
    4. Registered in the documents table.
    5. Returned to the browser as a downloadable file.
    """

    # ---------------------------------------------------------
    # 1. Generate document content
    # ---------------------------------------------------------
    try:
        content = generate_document_content(idea_id, document_type)

    except genai_errors.ClientError as exc:
        logger.exception("Gemini client error")
        raise HTTPException(
            status_code=502,
            detail=f"Gemini API rejected the request: {exc}",
        ) from exc

    except genai_errors.ServerError as exc:
        logger.exception("Gemini server error")
        raise HTTPException(
            status_code=502,
            detail=f"Gemini API had a server-side error: {exc}",
        ) from exc

    except ValueError as exc:
        logger.exception("Invalid document generated")
        raise HTTPException(
            status_code=502,
            detail=str(exc),
        ) from exc

    # ---------------------------------------------------------
    # 2. Render DOCX
    # ---------------------------------------------------------
    filepath = render_docx(content, document_type)

    # ---------------------------------------------------------
    # 3. Read generated DOCX
    # ---------------------------------------------------------
    try:
        with open(filepath, "rb") as file:
            file_bytes = file.read()

        # -----------------------------------------------------
        # 4. Find the student who owns this project
        # -----------------------------------------------------
        project_context = fetch_idea_with_student_context(idea_id)

        student_id = project_context.idea.student_id

        # -----------------------------------------------------
        # 5. Filename
        # -----------------------------------------------------
        filename = f"{document_type.value}.docx"

        # -----------------------------------------------------
        # 6. Save permanently to Supabase
        # -----------------------------------------------------
        save_document(
            student_id=student_id,
            idea_id=idea_id,
            document_type=document_type.value,
            file_name=filename,
            file_bytes=file_bytes,
        )

        logger.info(
            "Document stored successfully: idea=%s type=%s",
            idea_id,
            document_type.value,
        )

    except HTTPException:
        raise

    except Exception as exc:
        logger.exception("Failed to store generated document")
        raise HTTPException(
            status_code=500,
            detail=f"Document was generated but could not be stored: {exc}",
        ) from exc

    # ---------------------------------------------------------
    # 7. IMPORTANT:
    # Do NOT delete filepath here.
    #
    # FileResponse needs the temporary file to exist while the
    # response is being sent.
    # ---------------------------------------------------------
    return FileResponse(
        filepath,
        media_type=DOCX_MEDIA_TYPE,
        filename=filename,
    )